### PR TITLE
add angular 6 compatibility

### LINKED ISSUE #23: Angular 6 Support
Hey!
What do you think about adding Angular 6 Support?
I am not sure but i think it would not be possible to support older versions then... Maybe a ng6 branch? The Problem is that Angular 6 is using the RxJS v6 and there imports have changed. Also "takeUntil" now needs to be piped and stuff. I can make a PR for that but i don't know how you feel about the fact that this may lead to a breaking change in a way where it won't support older Angular versions anymore...

### PR DESCRIPTION
**Pull request by macjohnny**
fixes #23 

thanks to @Avejack for reporting and testing

### CODE REVIEW

**Comment by macjohnny** [comment]
@mtraynham unfortunately, we have to revert the changes introduced in #17 in order to be compatible with both, angular 5.x.x and 6.x.x

**Comment by macjohnny** [comment]
@mtraynham no need to apologize, thanks for your contribution ;)

I hope the tree-shaking is optimized with Angular CLI 6 and webpack 4...

**Comment by mtraynham** [comment]
@macjohnny Hey dude, so I believe I've figured out how it get's around this issue in Webpack 4.  There's a new flag called [`sideEffects` in Webpack](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free), that library authors can add to their `package.json` file.  This flag tells Webpack it can safely prune unused exports.  

RxJS has added this only recently, via https://github.com/ReactiveX/rxjs/pull/3385, so for 5.X usages of RxJS tree-shaking is still likely an issue, but I think that's beyond your scope of managing this library.  I'm just glad it's being handled somewhere.

**Comment by macjohnny** [comment]
@mtraynham thanks a lot for your investigation and posting the information here!
so it seems to be solved for newer versions.

concerning `ngx-mat-select-search` I would stay with the current solution that works properly with Angular 6 while still being backwards-compatible. If someone is bothered by the size of the imports, there is still the option to stick to version `1.0.5`. If someone is really bothered and thinks this might be worth it, we could also release another `1.0.x` version that includes the changes of `1.1.0`, without the rxjs import changes.

@mtraynham do you agree?

**Pull request merged**
