### PR TITLE
added search indicator spinner

### PR DESCRIPTION
**Pull request by mstawick**
Let me know if you have comments.

### CODE REVIEW

**Comment by macjohnny** [comment]
@mstawick could you also add the new input to the [API inputs](https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/README.md#inputs) section in the readme and use the new feature in the [server side search example](https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/src/app/examples/05-server-side-search-example/server-side-search-example.component.html#L7)?

**Comment by mstawick** [comment]
@macjohnny Updated

**Comment by macjohnny** [comment]
@mstawick thanks a lot for your contribution! I will release version `1.6.0` later today

**Comment by mstawick** [comment]
Super. Happy I could add my tiny improvement.

**Pull request merged**
