### PR TITLE
Revert "[FIX] Update previous selected values in mode multi (#377)"

### LINKED ISSUE #387: In multiselect, (selectionChange) event of the control does not contain all the elements but just the newly selected
Hey, this fix just broke my behavior! By modifying a copy of values but not the original one the `(selectionChange)` event of the control does not contain all the elements but just the newly selected.

@qstiegler Can you show me your usecase where version 4.1.1 threw an exception for you so I can maybe fix this?

_Originally posted by @angelaki in https://github.com/bithost-gmbh/ngx-mat-select-search/issues/376#issuecomment-1184489849_

### PR DESCRIPTION
**Pull request by macjohnny**
This reverts commit 1930d9a937aac41406e50a51e9540c86d5465a9c.

Fixes #387

### CODE REVIEW

**Comment by macjohnny** [comment]
cc @angelaki

**Comment by macjohnny** [comment]
@angelaki would you like to contribute a unit test for the (selectionChange) event?

**Comment by angelaki** [comment]
Sure, will check these days. Are there unit-tests alreay?

**Comment by macjohnny** [comment]
Yes, there are unit tests for single and multi selection

**Pull request merged**
