### PR TITLE
fix: if user selects first values by filtering and again second value by filtering itself

### LINKED ISSUE #270: [BUG] - Previously selected options getting deselect if modify the search
Describe the bug:
Previously selected options getting deselect if modify the search

To Reproduce:

Go to https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example
Scroll down to 'Multiple selection with Select All Checkbox'
Enter 'Bank C' in search
Click the select 'Bank C'
Select text 'Bank C' from search by double click on whole text or backspace and Change to 'Bank F'
Click the select 'Bank F'
Note the previously selected options have been removed

Expected behavior:
I expect Bank F should get selected from the list of options, with none of the currently selected options removed.

Addition information:
Getting this issue in: 
ngx-mat-select-search  version 3.1.0
angular-cli 10.0.5
angular-material 10.1.3

### PR DESCRIPTION
**Pull request by pranavneeraj**
fixes #270

### CODE REVIEW

**Comment by pranavneeraj** [comment]
Please review it. We have production on Monday. We need to test after merging. Thanks

**Comment by macjohnny** [comment]
@pranavneeraj thanks for the PR.
I will have a look at it and create a release in a few minutes

**Review by macjohnny — CHANGES_REQUESTED** [review]
Unfortunately, the fix breaks the following situation:
* go to "Multiple selection with Select All Checkbox"
* the initial selection is `K,L,M`
* enter "france" in the search box
* select the first entry "bank C"
* now the selection is `C` only

I found an alternative fix, which I am currently testing.

**Comment by macjohnny** [comment]
closing in favor of #272

**Pull request closed without merging**
